// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKwh5W6smkPpnkiyYKzAzM-HIxMejKjoE',
    appId: '1:102127627386:web:d5461e89d32b018b54dfc3',
    messagingSenderId: '102127627386',
    projectId: 'my-first-flutter-my-app',
    authDomain: 'my-first-flutter-my-app.firebaseapp.com',
    storageBucket: 'my-first-flutter-my-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzvtBtyp9E8gvWcYTN8jPZo1QBmq3JBQ4',
    appId: '1:102127627386:android:7247dbde61dd9cae54dfc3',
    messagingSenderId: '102127627386',
    projectId: 'my-first-flutter-my-app',
    storageBucket: 'my-first-flutter-my-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ-JtBjwopyhdgo3_kxJ2KhBBlDBYpMd4',
    appId: '1:102127627386:ios:73b2df573497d1e054dfc3',
    messagingSenderId: '102127627386',
    projectId: 'my-first-flutter-my-app',
    storageBucket: 'my-first-flutter-my-app.appspot.com',
    iosClientId: '102127627386-nssael1vsgtlvljo1n3i10jbrav6i8i8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ-JtBjwopyhdgo3_kxJ2KhBBlDBYpMd4',
    appId: '1:102127627386:ios:44aeacf74f9c65e654dfc3',
    messagingSenderId: '102127627386',
    projectId: 'my-first-flutter-my-app',
    storageBucket: 'my-first-flutter-my-app.appspot.com',
    iosClientId: '102127627386-qn1ori9r7f5tc76f7fdnkqvbnv3j48hh.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
